### ISSUE TITLE
Outstanding game, but it is clearly missing a feature

### ISSUE THREAD

**Issue by MagiHotline** [dddema/tictactoe#1]
## Good evening, tictactoe creators,

I just downloaded your game and it was truly entertaining. When the confetti appeared, I was absolutely stunned by the beauty of the animation. Nevertheless, there's a **missing** feature. The numbers of games played is NOT displayed even though it's clearly there, I see it staring at me menacingly. So I suggest to fix this little incomprehension because it would help the game to be more entertaining and fun for the users. And as a friend of main used to say:

> Che grande.

So... run it back:

- [x] Fix the number of games played
- [x] Fix the number of wins, losses and draws
- [x] Add some cool features, like cats

And with that said, goodnight everyone!

from Magi

**Comment by dddema** [comment]
All the things to "fix" mentioned, do in fact work. Its just that you were probably using a **chromium based browser** and opening the file from local (`file://`), and not using a webserver to run it (so accessing the page via: `http://`). Chromium doesn't save cookies if there is no reason to do so (i.e. a communication with a server that creates a session), safari on the other end does.

Cats added.

_Sorry for the delay,
DDM_
